# Generated by Django 3.2.4 on 2023-07-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ourinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourinformation',
            name='tell',
            field=models.IntegerField(),
        ),
    ]
